---
name: Trilium Next
version: v0.90.4
upstream: v0.90.4
slug: triliumnext
description: The most powerful and extensible open source Wiki software
url: https://github.com/FaserF/hassio-addons/tree/master/wiki.js
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
services:
  - mysql:need
startup: application
boot: auto
map:
  - ssl
ingress: true
ingress_port: 80
ingress_stream: true
init: false
auth_api: true
panel_icon: mdi:wikipedia
options:
  ssl: true
  certfile: cert_openssl.pem
  keyfile: key_openssl.pem
  log_level: info
ports:
  3000/tcp: 3002
  3443/tcp: 3443
ports_description:
  3000/tcp: HTTP Entrance port
  3443/tcp: HTTPS/SSL Entrance port
schema:
  ssl: bool
  certfile: str
  keyfile: str
  log_level: list(error|warn|info|debug)?
  reset_database: bool?
